- name: Deploy frontend
  hosts: local
  gather_facts: false
  vars_files: [ ../group_vars.yml ]
  collections: [ kubernetes.core ]
  vars:
    ns: webapps
    frontend_image: "docker.io/chiomavee/frontend:latest"  # TODO change if needed
  tasks:
    - name: frontend service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata: { name: frontend-svc, namespace: "{{ ns }}" }
          spec:
            selector: { app: frontend }
            ports:
              - port: 80
                targetPort: 80

    - name: frontend deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata: { name: frontend, namespace: "{{ ns }}" }
          spec:
            replicas: 2
            selector: { matchLabels: { app: frontend } }
            template:
              metadata: { labels: { app: frontend } }
              spec:
                containers:
                  - name: web
                    image: "{{ frontend_image }}"
                    ports: [ { containerPort: 80 } ]
                    env:
                      - name: REACT_APP_API_URL
                        value: "http://backend-svc.webapps.svc.cluster.local:8080"
                    readinessProbe:
                      httpGet: { path: "/", port: 80 }
                      initialDelaySeconds: 10
                    livenessProbe:
                      httpGet: { path: "/", port: 80 }
                      initialDelaySeconds: 30
