---
- name: Apply app secrets
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    kubeconfig: "{{ lookup('env','HOME') }}/.kube/config"
  collections:
    - kubernetes.core

  tasks:
    - name: Create YelpCamp app secrets
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: app-secrets
            namespace: webapps
          type: Opaque
          stringData:
            CLOUDINARY_CLOUD_NAME: "dirgvlukt"
            CLOUDINARY_KEY: "965925471914912"
            CLOUDINARY_SECRET: "9YfliE2mmBQELF7pxbilIivrCC0"
            MAPBOX_TOKEN: "pk.eyJ1IjoiY2hpb21hdmVlIiwiYSI6ImNtZmVlaW9mOTAzY2cya3BiaDF1cDd1NjIifQ.qLSXFZLDFVxCqOPWCOSGmg"
            DB_URL: "mongodb+srv://chiomavanessa8_db_user:LmzaEWHiz41NRWWe@cadd2.z8kn2ny.mongodb.net/yelpcamp?retryWrites=true&w=majority&appName=cadd2"
            SECRET: "123456"
